api = "0.4"

[buildpack]
id = "malax/rust-cnb-starter"
version = "1.0.0"
name = "rust-cnb-starter"
clear-env = true
homepage = "https://github.com/malax/rust-cnb-starter"
description = "Template project for Cloud Native Buildpacks written in the Rust programming language"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
